org.gradle.jvmargs=-Xmx3G -Dfile.encoding=UTF-8
org.gradle.parallel=true
kotlin.code.style=official

core_java_version=17
org.gradle.java.installations.fromEnv=COMPOSEMC_JDK17,COMPOSEMC_JDK21,COMPOSEMC_JDK25
mod_id=composemc
mod_name=Compose MC
mod_license=MIT
mod_version=0.1.0-alpha.34
loader_version_range=[1,)
